export const SEED = [
  {
    id: 101,
    title: "Bache profundo en Av. Alemania",
    summary: "Hueco de ~50 cm que afecta la pista derecha, riesgo para motos.",
    description: "El bache lleva 2 semanas. Señalética improvisada con cono roto.",
    category: "Vialidad",
    urgency: "alta",
    status: "pendiente",
    votes: 128,
    image: "/imgs/reportes/bache-alemania.jpg",
    address: "Av. Alemania 0420, Temuco",
    user: "Juan P.",
    createdAt: "2025-10-16T14:35:00-03:00"
  },
  {
    id: 102,
    title: "Luminaria apagada en pasaje",
    summary: "Farol peatonal sin encender hace 4 noches.",
    description: "Oscuridad total entre las 20:00 y 06:00. Zona de alto tránsito.",
    category: "Alumbrado",
    urgency: "media",
    status: "pendiente",
    votes: 37,
    image: null,
    address: "Pasaje Los Notros 115, Temuco",
    user: "Carla U.",
    createdAt: "2025-10-15T21:10:00-03:00"
  },
  {
    id: 103,
    title: "Semáforo descoordinado en centro",
    summary: "Ciclo verde demasiado corto provoca atochamiento.",
    description: "Cruce Caupolicán con Portales. Verde dura ~8 s en hora punta.",
    category: "Semáforos",
    urgency: "alta",
    status: "en_proceso",
    votes: 89,
    image: "/imgs/reportes/semaforo-centro.png",
    address: "Manuel Bulnes 720, Temuco",
    user: "Marcos V.",
    createdAt: "2025-10-14T08:50:00-03:00"
  },
  {
    id: 104,
    title: "Acumulación de basura",
    summary: "Microbasural en esquina, malos olores.",
    description: "Se observan bolsas abiertas y escombros livianos.",
    category: "Aseo",
    urgency: "media",
    status: "pendiente",
    votes: 24,
    image: null,
    address: "Los Carrera con Diego Portales, Temuco",
    user: "Ana R.",
    createdAt: "2025-10-13T10:12:00-03:00"
  },
  {
    id: 105,
    title: "Tapa de alcantarilla suelta",
    summary: "Peligro para ciclistas, suena y se desplaza al pasar vehículos.",
    description: "Necesita ajuste/recambio de pernos.",
    category: "Sanitario",
    urgency: "alta",
    status: "pendiente",
    votes: 61,
    image: "/imgs/reportes/alcantarilla.jpg",
    address: "Av. Pablo Neruda 1300, Temuco",
    user: "Ismael D.",
    createdAt: "2025-10-12T19:05:00-03:00"
  },
  {
    id: 106,
    title: "Vereda quebrada frente a consultorio",
    summary: "Losas levantadas ~3 cm, riesgo de tropiezos.",
    description: "Afecta acceso universal a personas mayores.",
    category: "Veredas",
    urgency: "alta",
    status: "en_proceso",
    votes: 42,
    image: null,
    address: "Av. Prieto Norte 255, Temuco",
    user: "Sofía G.",
    createdAt: "2025-10-11T11:33:00-03:00"
  },
  {
    id: 107,
    title: "Señal de PARE caída",
    summary: "Poste doblado, disco casi al ras del suelo.",
    description: "Intersección peligrosa para buses escolares.",
    category: "Señalización",
    urgency: "alta",
    status: "pendiente",
    votes: 77,
    image: "/imgs/reportes/pare-caida.webp",
    address: "Pedro de Valdivia con Barros Arana, Temuco",
    user: "Luis T.",
    createdAt: "2025-10-10T07:20:00-03:00"
  },
  {
    id: 108,
    title: "Fuga de agua en calzada",
    summary: "Chorro constante desde fisura, se forma poza.",
    description: "Pérdida visible incluso de madrugada.",
    category: "Agua Potable",
    urgency: "alta",
    status: "en_proceso",
    votes: 53,
    image: null,
    address: "Av. Balmaceda 980, Temuco",
    user: "Verónica H.",
    createdAt: "2025-10-09T23:41:00-03:00"
  },
  {
    id: 109,
    title: "Árbol a punto de caer",
    summary: "Raíces expuestas, se inclinó tras temporal.",
    description: "Podría dañar reja y cableado cercano.",
    category: "Áreas Verdes",
    urgency: "alta",
    status: "pendiente",
    votes: 35,
    image: "/imgs/reportes/arbol-inestable.jpg",
    address: "Parque Estadio Germán Becker, Temuco",
    user: "Natalia Q.",
    createdAt: "2025-10-09T14:02:00-03:00"
  },
  {
    id: 110,
    title: "Paradero sin techo",
    summary: "Estructura dañada, usuarios quedan a la intemperie.",
    description: "Restos de policarbonato quebrado en el suelo.",
    category: "Transporte",
    urgency: "media",
    status: "pendiente",
    votes: 12,
    image: null,
    address: "Av. Las Encinas 560, Temuco",
    user: "Pedro S.",
    createdAt: "2025-10-08T18:25:00-03:00"
  },
  {
    id: 111,
    title: "Calzada con hoyos menores",
    summary: "Varios pequeños baches en pista izquierda.",
    description: "Se agravan con la lluvia; proponer bacheo frío.",
    category: "Vialidad",
    urgency: "baja",
    status: "resuelto",
    votes: 8,
    image: "/imgs/reportes/hoyos-menores.jpg",
    address: "Av. Pedro de Valdivia 1600, Temuco",
    user: "Romina E.",
    createdAt: "2025-10-07T09:10:00-03:00"
  },
  {
    id: 112,
    title: "Rejilla de desagüe obstruida",
    summary: "Hojas y residuos impiden escurrimiento.",
    description: "Se inunda calzada tras 15 min de lluvia.",
    category: "Drenaje",
    urgency: "media",
    status: "en_proceso",
    votes: 21,
    image: null,
    address: "Av. San Martín 350, Temuco",
    user: "Diego C.",
    createdAt: "2025-10-06T16:45:00-03:00"
  },
  {
    id: 113,
    title: "Cruce peatonal sin pintura",
    summary: "Cebra casi invisible, riesgo para escolares.",
    description: "Solicita demarcación urgente antes de fin de mes.",
    category: "Señalización",
    urgency: "media",
    status: "pendiente",
    votes: 44,
    image: "/imgs/reportes/cebra-desgastada.jpg",
    address: "Lircay con Javiera Carrera, Temuco",
    user: "Estefanía M.",
    createdAt: "2025-10-05T12:18:00-03:00"
  },
  {
    id: 114,
    title: "Rotura de tubería menor en plaza",
    summary: "Riego rompe y moja vereda continuamente.",
    description: "Se genera barro; resbaladizo para niños.",
    category: "Áreas Verdes",
    urgency: "baja",
    status: "pendiente",
    votes: 5,
    image: null,
    address: "Plaza Aníbal Pinto, Temuco",
    user: "Camila Y.",
    createdAt: "2025-10-04T08:05:00-03:00"
  },
  {
    id: 115,
    title: "Pozo sin tapa señalizado",
    summary: "Tapa robada, hay valla pero es inestable.",
    description: "Riesgo alto en la noche por baja visibilidad.",
    category: "Sanitario",
    urgency: "alta",
    status: "en_proceso",
    votes: 73,
    image: "/imgs/reportes/pozo-sin-tapa.jpg",
    address: "Av. O'Higgins 910, Temuco",
    user: "Matías L.",
    createdAt: "2025-10-03T20:32:00-03:00"
  },
  {
    id: 116,
    title: "Basurero público quebrado",
    summary: "Contenedor metálico con borde filoso.",
    description: "Riesgo de cortes; requiere retiro.",
    category: "Aseo",
    urgency: "baja",
    status: "resuelto",
    votes: 3,
    image: null,
    address: "Av. León Gallo 270, Temuco",
    user: "Patricio Z.",
    createdAt: "2025-10-03T09:14:00-03:00"
  },
  {
    id: 117,
    title: "Baranda suelta en puente peatonal",
    summary: "Anclajes flojos en tramo central.",
    description: "Vibración notoria al pasar 3+ personas.",
    category: "Infraestructura",
    urgency: "alta",
    status: "pendiente",
    votes: 66,
    image: "/imgs/reportes/baranda-puente.png",
    address: "Puente peatonal Av. Caupolicán, Temuco",
    user: "Nicole B.",
    createdAt: "2025-10-02T18:55:00-03:00"
  },
  {
    id: 118,
    title: "Hueco en berma rural",
    summary: "Profundidad ~25 cm, autos se desestabilizan.",
    description: "Ruta S-30 camino a Labranza, km 4,3.",
    category: "Vialidad",
    urgency: "media",
    status: "pendiente",
    votes: 14,
    image: null,
    address: "Camino a Labranza, km 4,3, Temuco",
    user: "Ricardo A.",
    createdAt: "2025-10-01T07:30:00-03:00"
  },
  {
    id: 119,
    title: "Alcantarilla con mal olor",
    summary: "Hediondez constante por las tardes.",
    description: "Podría haber obstrucción aguas servidas.",
    category: "Sanitario",
    urgency: "media",
    status: "pendiente",
    votes: 19,
    image: null,
    address: "Montt 520, Temuco",
    user: "Graciela J.",
    createdAt: "2025-09-30T19:40:00-03:00"
  },
  {
    id: 120,
    title: "Poste con cables colgando",
    summary: "Cables de baja altura rozan camiones.",
    description: "Probablemente telecomunicaciones, riesgo de enganche.",
    category: "Electricidad/Telecom",
    urgency: "alta",
    status: "en_proceso",
    votes: 58,
    image: "/imgs/reportes/cables-colgando.jpg",
    address: "Av. Los Poetas 150, Temuco",
    user: "Bastián S.",
    createdAt: "2025-09-29T13:22:00-03:00"
  }
];
